### ISSUE TITLE
Accounts Option / Restricted Contents

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#24]
Would it be possible to eventually have an option for user accounts (such as access to basic information for no user, or secure information with a verified account system)? I feel this would be useful for multiple cases:

**Business:** Stops outside users from accessing content, authorized users are able to see the content based on group (standard would have access to standard content, while admin would have full access).

**Collaboration Projects:** Standard members have access to the basic views, where team leaders have extra options for behind the scenes or more private information.

**Personal Wiki:** Shares the basic info with friends, but keeps private information behind an account.

While not needed for editing articles (such as Wikipedia), I think it would be nice to have some form of authorization to keep specific information apart depending on the user type accessing it instead of having multiple wikis (one public, one private). If nothing else, it would be useful to help ensure specific people or accounts have access to information.

If you wanted to go one step further (again, not required, but an interesting idea I had), you could offer either comments and/or feedback boxes so users / viewers could inform the wiki manager of an update or error or discuss the quality of the article, depending on the type of site.

As always, merely a suggestion, but I think some sort of account situation would be very useful in the long run.

**Comment by hang-up** [comment]
Although I 100% agree with you on how an authorization / user role management would make sense business wise, I don't think it fits the core values of Bük. 
Indeed, at its core, Bük is simply a tool capable of generating a static site geared towards documentation. Input a bunch of markdown files and output an out of the box ready to be deployed website (this is even more flagrant in 3.1). At the end of the day, there should not be any client-server interaction apart from the first time loading the website (in order to cache all of it).

The use cases you point out can be solved with tools used along side of Bük. 
For example, user role management can be setup by spinning up a (php/node/...) server and requiring some amazing frameworks (Laravel / Express / ...). 
Additionally those packages would probably do a better job than an all front end Javascript solution offered by Bük ;)

I am nonetheless very interested with your last "going one step further" idea: a report button or feedback box would be amazingly useful. 
I'll start experimenting!

Again, thanks for those ideas, it brings a tremendous value to the project!
