### ISSUE TITLE
SSL Compatability?

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#31]
Through development while adding Bük to our authentication portal (iFrame), it appears some web browsers (chrome in this case) panic when trying to insert non-SSL content into an SSL protected page. Is there some way to SSL-enable the wiki?

**Comment by lloyd094** [comment]
Just a quick bump - any ideas?

**Comment by hang-up** [comment]
Whoops my bad! Got caught up and skipped this one...
Truth is, I don't think there is a way to "SSL-enable" Bük. Since the outputted files can basically be self-hosted on your own server (from within the `dist` folder), you should be able to distribute them in https. 
There are resources on stackoverflow as of how to do this, for example : https://stackoverflow.com/questions/18327314/how-to-allow-http-content-within-an-iframe-on-a-https-site

**Comment by lloyd094** [comment]
Thanks for the reply and link! I will see what we can figure out - I've already requested getting some more details, so I'll see if I can narrow it down. I will keep the thread updated just in case!

**Comment by lloyd094** [comment]
Closing this - turns out it wasn't an issue with Bük, and was more of a problem with the software we were using. Thanks for the help!
